### PR TITLE
deps: update async-io, if-addrs, env_logger

### PR DESCRIPTION
**Pull request by kayabaNerve**
The commit messages justify each change, though if the async-io update isn't preferable at this time, the if-addrs commit alone can be cherry-picked for the firm improvements provided.

I believe all this can fit in a patch release.

### CODE REVIEW

**Comment by kayabaNerve** [comment]
Oh. I also debated updating rtnetlink (the remaining package with an incompatible update available). It can only be updated to 0.11, which added features not needed here. Updating to 0.12 would remove their use of re-exports, and require adding more crates to if-watch's Cargo.toml. While I wouldn't be against that if there was a reason to update, I see no actual bug fixes and I don't care to be so invasive at this time.

If someone is using the newly added features of rtnetlink, they may want to request an update to if-watch to not have multiple versions in their tree, though I'd rather my PRs offer a more direct justification.

**Review by mxinden — COMMENTED** [review]
Thank you.

Would you mind bumping the patch version and adding a changelog entry?

Also, to make this easier on you, want to create a pull request adding @dependabot?

**Comment by mxinden** [comment]
Minor version, given that we are > 1.0

**Comment by kayabaNerve** [comment]
@mxinden Friendly reminder I did bump the patch version and added a changelog entry, as requested :)

**Review by mxinden — APPROVED** [review]
Thank you for the help.

Sorry for the delay.

**Comment by mxinden** [comment]
[Published](https://crates.io/crates/if-watch/3.2.0) and [tagged](https://github.com/mxinden/if-watch/releases/tag/v3.2.0).

**Pull request merged**
