### PR TITLE
windows 0.51

### PR DESCRIPTION
**Pull request by kayabaNerve**
While this compiles, I'm unsure if it effects msrv/if Some(callback) is as expected. I'd hope the CI's tests to catch any errors, as I do not have a windows machine to actually run this one.

### CODE REVIEW

**Comment by mxinden** [comment]
Thank you for the patch.



> While this compiles, I'm unsure if it effects msrv/if Some(callback) is as expected.

In what way would this pull request be a breaking change? In other words, what of `windows` is exposed through `if-watch`?

> While this compiles, I'm unsure if it effects msrv/if Some(callback) is as expected. I'd hope the CI's tests to catch any errors, as I do not have a windows machine to actually run this one.

Me neither. Do you know anyone? What was your initial motivation to propose this patch?

**Comment by kayabaNerve** [comment]
It'd be a breaking change if a party expects if-watch to run on Rust 1.xy, which windows 0.34 does, yet windows 0.51 does not. I didn't evaluate the msrv of windows to see if windows 0.51 increased its msrv when compared to 0.34, and am unsure what if-watch's current/advertised msrv is.

The motivation for the patch was to reduce tree size. Right now, I have several windows crates in tree *which no other dependency uses as they're over a year old*. I then also have windows 0.48 in tree by project(s) which do maintain their windows dependencies (please note there was no 0.49 nor 0.50, and 0.51 is only a month old). It's just unappreciated to have both contribute to my disk space and compile times. While I could've been greedy and simply updated if-watch to 0.48, for my immediate happiness, I'd rather everyone in the ecosystem do their best to stay up to date.

This was solely an attempt to be that person keeping things up to date, rather than silently expecting random people on the internet do so.

**Comment by kayabaNerve** [comment]
@mxinden The CI does test against a Windows host, so this should be verified if you let the CI run.

**Review by mxinden — APPROVED** [review]
Thank you for the help!

**Comment by mxinden** [comment]
[Tagged](https://github.com/mxinden/if-watch/releases/tag/v3.1.0) and [published](https://crates.io/crates/if-watch/3.1.0).

**Pull request merged**
